//+------------------------------------------------------------------+
//|                                        BT_AwesomeOscillator.mq5 |
//|              Custom indicator — Generated by Backtester Rust      |
//|   AO = SMA(midpoint, 5) - SMA(midpoint, 34)                     |
//|   midpoint = (High + Low) / 2                                    |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "AO"
#property indicator_type1   DRAW_HISTOGRAM
#property indicator_color1  clrDodgerBlue
#property indicator_width1  2

double AoBuffer[];

int OnInit()
{
   SetIndexBuffer(0, AoBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, 34);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_AO");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 34) return 0;

   int start = (prev_calculated == 0) ? 33 : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < 33; i++)
         AoBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      // SMA(midpoint, 5)
      double sum5 = 0;
      for(int j = i - 4; j <= i; j++)
         sum5 += (high[j] + low[j]) / 2.0;
      double sma5 = sum5 / 5.0;

      // SMA(midpoint, 34)
      double sum34 = 0;
      for(int j = i - 33; j <= i; j++)
         sum34 += (high[j] + low[j]) / 2.0;
      double sma34 = sum34 / 34.0;

      AoBuffer[i] = sma5 - sma34;
   }

   return rates_total;
}
