//+------------------------------------------------------------------+
//|                                                      BT_ATR.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact ATR calculation from backtester engine.        |
//|   Uses Wilder's smoothing: ATR = (prev*(N-1) + TR) / N           |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "ATR"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1

input int InpPeriod = 14; // Period

double AtrBuffer[];

// Internal state for Wilder's smoothing
double gAtr = 0;
bool   gSeeded = false;

int OnInit()
{
   SetIndexBuffer(0, AtrBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_ATR(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         AtrBuffer[i] = EMPTY_VALUE;

      // Compute TR and first ATR as SMA of first 'period' TR values
      // TR[0] = high[0] - low[0]
      double sumTR = high[0] - low[0];
      for(int i = 1; i < InpPeriod; i++)
      {
         double hl = high[i] - low[i];
         double hc = MathAbs(high[i] - close[i - 1]);
         double lc = MathAbs(low[i] - close[i - 1]);
         sumTR += MathMax(hl, MathMax(hc, lc));
      }
      gAtr = sumTR / InpPeriod;
      AtrBuffer[InpPeriod - 1] = gAtr;
      gSeeded = true;
      start = InpPeriod;
   }
   else
   {
      start = prev_calculated - 1;
   }

   // Wilder's smoothing: ATR = (prev_ATR * (period-1) + TR) / period
   for(int i = start; i < rates_total; i++)
   {
      double hl = high[i] - low[i];
      double hc = MathAbs(high[i] - close[i - 1]);
      double lc = MathAbs(low[i] - close[i - 1]);
      double tr = MathMax(hl, MathMax(hc, lc));

      gAtr = (gAtr * (InpPeriod - 1) + tr) / InpPeriod;
      AtrBuffer[i] = gAtr;
   }

   return rates_total;
}
