//+------------------------------------------------------------------+
//|                                                    BT_Aroon.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Aroon Up   = ((period - bars since highest high) / period)*100 |
//|   Aroon Down = ((period - bars since lowest  low ) / period)*100 |
//|   Buffer 0: AroonUp, Buffer 1: AroonDown                         |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 2
#property indicator_plots   2
#property indicator_label1  "AroonUp"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_label2  "AroonDown"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrRed
#property indicator_width2  1
#property indicator_minimum 0
#property indicator_maximum 100

input int InpPeriod = 14; // Period

double AroonUpBuffer[];
double AroonDownBuffer[];

int OnInit()
{
   SetIndexBuffer(0, AroonUpBuffer,   INDICATOR_DATA);
   SetIndexBuffer(1, AroonDownBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetInteger(1, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   PlotIndexSetDouble(1,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_Aroon(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   int start = (prev_calculated == 0) ? InpPeriod : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod; i++)
      {
         AroonUpBuffer[i]   = EMPTY_VALUE;
         AroonDownBuffer[i] = EMPTY_VALUE;
      }
   }

   for(int i = start; i < rates_total; i++)
   {
      int    startIdx = i - InpPeriod;
      double maxH     = high[startIdx];
      double minL     = low[startIdx];
      int    maxIdx   = startIdx;
      int    minIdx   = startIdx;

      for(int j = startIdx + 1; j <= i; j++)
      {
         if(high[j] > maxH) { maxH = high[j]; maxIdx = j; }
         if(low[j]  < minL) { minL = low[j];  minIdx = j; }
      }

      AroonUpBuffer[i]   = ((double)(InpPeriod - (i - maxIdx)) / (double)InpPeriod) * 100.0;
      AroonDownBuffer[i] = ((double)(InpPeriod - (i - minIdx)) / (double)InpPeriod) * 100.0;
   }

   return rates_total;
}
