//+------------------------------------------------------------------+
//|                                               BT_BullsPower.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Bulls Power = High - EMA(Close, period)                        |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "BullsPower"
#property indicator_type1   DRAW_HISTOGRAM
#property indicator_color1  clrGreen
#property indicator_width1  1

input int InpPeriod = 13; // Period

double BullsBuffer[];

// EMA state
double gEma    = 0;
bool   gSeeded = false;

int OnInit()
{
   SetIndexBuffer(0, BullsBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_BullsPower(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   double multiplier = 2.0 / (InpPeriod + 1.0);

   int start;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         BullsBuffer[i] = EMPTY_VALUE;

      // Seed EMA with SMA of first 'period' closes
      double sum = 0;
      for(int i = 0; i < InpPeriod; i++)
         sum += close[i];
      gEma = sum / InpPeriod;
      BullsBuffer[InpPeriod - 1] = high[InpPeriod - 1] - gEma;
      gSeeded = true;
      start = InpPeriod;
   }
   else
   {
      start = prev_calculated - 1;
   }

   for(int i = start; i < rates_total; i++)
   {
      gEma = (close[i] - gEma) * multiplier + gEma;
      BullsBuffer[i] = high[i] - gEma;
   }

   return rates_total;
}
