//+------------------------------------------------------------------+
//|                                          BT_BollingerBands.mq5    |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact Bollinger Bands from backtester engine.        |
//|   Uses population std dev (divide by N, NOT N-1).                 |
//|   Buffer 0: Middle (SMA), Buffer 1: Upper, Buffer 2: Lower       |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 3
#property indicator_plots   3
#property indicator_label1  "Middle"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_label2  "Upper"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrGray
#property indicator_width2  1
#property indicator_label3  "Lower"
#property indicator_type3   DRAW_LINE
#property indicator_color3  clrGray
#property indicator_width3  1

input int    InpPeriod = 20;  // Period
input double InpStdDev = 2.0; // Std Dev Multiplier

double MiddleBuffer[];
double UpperBuffer[];
double LowerBuffer[];

int OnInit()
{
   // Buffer order matches Rust: primary=middle(0), secondary=upper(1), tertiary=lower(2)
   SetIndexBuffer(0, MiddleBuffer, INDICATOR_DATA);
   SetIndexBuffer(1, UpperBuffer, INDICATOR_DATA);
   SetIndexBuffer(2, LowerBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetInteger(1, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetInteger(2, PLOT_DRAW_BEGIN, InpPeriod);
   for(int i = 0; i < 3; i++)
      PlotIndexSetDouble(i, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME,
      "BT_BB(" + IntegerToString(InpPeriod) + "," + DoubleToString(InpStdDev, 1) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
      {
         MiddleBuffer[i] = EMPTY_VALUE;
         UpperBuffer[i] = EMPTY_VALUE;
         LowerBuffer[i] = EMPTY_VALUE;
      }
   }

   for(int i = start; i < rates_total; i++)
   {
      // SMA (middle band)
      double sum = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
         sum += close[j];
      double mean = sum / InpPeriod;
      MiddleBuffer[i] = mean;

      // Population standard deviation (matching Rust: divide by N, not N-1)
      double variance = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
      {
         double diff = close[j] - mean;
         variance += diff * diff;
      }
      variance /= InpPeriod;
      double sd = MathSqrt(variance);

      UpperBuffer[i] = mean + InpStdDev * sd;
      LowerBuffer[i] = mean - InpStdDev * sd;
   }

   return rates_total;
}
