//+------------------------------------------------------------------+
//|                                                      BT_CCI.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact CCI calculation from backtester engine.        |
//|   CCI = (TP - SMA(TP)) / (0.015 * MeanDeviation)                 |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "CCI"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_level1  100
#property indicator_level2  -100

input int InpPeriod = 20; // Period

double CciBuffer[];

int OnInit()
{
   SetIndexBuffer(0, CciBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_CCI(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         CciBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      // Typical price for current bar
      double tp_i = (high[i] + low[i] + close[i]) / 3.0;

      // SMA of typical prices over period
      double sum = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
         sum += (high[j] + low[j] + close[j]) / 3.0;
      double mean = sum / InpPeriod;

      // Mean deviation
      double meanDev = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
      {
         double tp_j = (high[j] + low[j] + close[j]) / 3.0;
         meanDev += MathAbs(tp_j - mean);
      }
      meanDev /= InpPeriod;

      CciBuffer[i] = (meanDev == 0) ? 0 : (tp_i - mean) / (0.015 * meanDev);
   }

   return rates_total;
}
