//+------------------------------------------------------------------+
//|                                                BT_DeMarker.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   DeMarker = SMA(DeMax,p) / (SMA(DeMax,p) + SMA(DeMin,p))       |
//|   DeMax[i] = max(High[i]-High[i-1], 0)                          |
//|   DeMin[i] = max(Low[i-1]-Low[i],  0)                           |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "DeMarker"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_level1  0.7
#property indicator_level2  0.3
#property indicator_minimum 0
#property indicator_maximum 1

input int InpPeriod = 14; // Period

double DemBuffer[];

int OnInit()
{
   SetIndexBuffer(0, DemBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_DeMarker(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   int start = (prev_calculated == 0) ? InpPeriod : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod; i++)
         DemBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      // Rolling SMA of DeMax and DeMin over [i-period+1 .. i]
      double sumMax = 0;
      double sumMin = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
      {
         double deMax = MathMax(high[j] - high[j - 1], 0);
         double deMin = MathMax(low[j - 1] - low[j],  0);
         sumMax += deMax;
         sumMin += deMin;
      }
      double smaMax = sumMax / InpPeriod;
      double smaMin = sumMin / InpPeriod;
      double denom  = smaMax + smaMin;
      DemBuffer[i]  = (denom == 0) ? 0.5 : smaMax / denom;
   }

   return rates_total;
}
