//+------------------------------------------------------------------+
//|                                                      BT_EMA.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact EMA calculation from backtester engine.        |
//|   Seed: SMA of first N values. Multiplier: 2/(period+1).         |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "EMA"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrOrangeRed
#property indicator_width1  1

input int InpPeriod = 14; // Period

double EmaBuffer[];

int OnInit()
{
   SetIndexBuffer(0, EmaBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_EMA(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   double multiplier = 2.0 / (InpPeriod + 1.0);

   int start;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         EmaBuffer[i] = EMPTY_VALUE;

      // Seed with SMA of first 'period' values
      double sum = 0;
      for(int i = 0; i < InpPeriod; i++)
         sum += close[i];
      EmaBuffer[InpPeriod - 1] = sum / InpPeriod;
      start = InpPeriod;
   }
   else
   {
      start = prev_calculated - 1;
   }

   for(int i = start; i < rates_total; i++)
   {
      EmaBuffer[i] = (close[i] - EmaBuffer[i - 1]) * multiplier + EmaBuffer[i - 1];
   }

   return rates_total;
}
