//+------------------------------------------------------------------+
//|                                                  BT_Fractal.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Williams 5-bar Fractal (confirmed 2 bars after peak/trough)    |
//|   Buffer 0: FractalUp (arrow 217), Buffer 1: FractalDown (218)   |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 2
#property indicator_plots   2
#property indicator_label1  "FractalUp"
#property indicator_type1   DRAW_ARROW
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_label2  "FractalDown"
#property indicator_type2   DRAW_ARROW
#property indicator_color2  clrRed
#property indicator_width2  1

double FractalUpBuffer[];
double FractalDownBuffer[];

int OnInit()
{
   SetIndexBuffer(0, FractalUpBuffer,   INDICATOR_DATA);
   SetIndexBuffer(1, FractalDownBuffer, INDICATOR_DATA);

   PlotIndexSetInteger(0, PLOT_ARROW,       217);
   PlotIndexSetInteger(1, PLOT_ARROW,       218);
   PlotIndexSetInteger(0, PLOT_ARROW_SHIFT, 0);
   PlotIndexSetInteger(1, PLOT_ARROW_SHIFT, 0);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN,  4);
   PlotIndexSetInteger(1, PLOT_DRAW_BEGIN,  4);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   PlotIndexSetDouble(1,  PLOT_EMPTY_VALUE, EMPTY_VALUE);

   IndicatorSetString(INDICATOR_SHORTNAME, "BT_Fractal");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 5) return 0;

   // Always recalc from start (stateful — fractals depend on surrounding bars)
   ArrayInitialize(FractalUpBuffer,   EMPTY_VALUE);
   ArrayInitialize(FractalDownBuffer, EMPTY_VALUE);

   for(int i = 4; i < rates_total; i++)
   {
      int mid = i - 2;

      // FractalUp: mid's high is highest among 5 bars
      if(high[mid] > high[mid - 2] &&
         high[mid] > high[mid - 1] &&
         high[mid] > high[mid + 1] &&
         high[mid] > high[mid + 2])
      {
         FractalUpBuffer[i] = high[mid];
      }

      // FractalDown: mid's low is lowest among 5 bars
      if(low[mid] < low[mid - 2] &&
         low[mid] < low[mid - 1] &&
         low[mid] < low[mid + 1] &&
         low[mid] < low[mid + 2])
      {
         FractalDownBuffer[i] = low[mid];
      }
   }

   return rates_total;
}
