//+------------------------------------------------------------------+
//|                                                BT_Fibonacci.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Rolling Fibonacci retracement levels over period bars          |
//|   Buffer 0=Fib236, 1=Fib382, 2=Fib500, 3=Fib618, 4=Fib786      |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 5
#property indicator_plots   5
#property indicator_label1  "Fib236"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrGold
#property indicator_style1  STYLE_DOT
#property indicator_width1  1
#property indicator_label2  "Fib382"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrOrangeRed
#property indicator_style2  STYLE_DOT
#property indicator_width2  1
#property indicator_label3  "Fib500"
#property indicator_type3   DRAW_LINE
#property indicator_color3  clrMagenta
#property indicator_style3  STYLE_DASH
#property indicator_width3  1
#property indicator_label4  "Fib618"
#property indicator_type4   DRAW_LINE
#property indicator_color4  clrDodgerBlue
#property indicator_style4  STYLE_DOT
#property indicator_width4  1
#property indicator_label5  "Fib786"
#property indicator_type5   DRAW_LINE
#property indicator_color5  clrLimeGreen
#property indicator_style5  STYLE_DOT
#property indicator_width5  1

input int InpPeriod = 50; // Period

double Fib236Buffer[];
double Fib382Buffer[];
double Fib500Buffer[];
double Fib618Buffer[];
double Fib786Buffer[];

int OnInit()
{
   SetIndexBuffer(0, Fib236Buffer, INDICATOR_DATA);
   SetIndexBuffer(1, Fib382Buffer, INDICATOR_DATA);
   SetIndexBuffer(2, Fib500Buffer, INDICATOR_DATA);
   SetIndexBuffer(3, Fib618Buffer, INDICATOR_DATA);
   SetIndexBuffer(4, Fib786Buffer, INDICATOR_DATA);

   for(int p = 0; p < 5; p++)
   {
      PlotIndexSetInteger(p, PLOT_DRAW_BEGIN, InpPeriod - 1);
      PlotIndexSetDouble(p,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   }

   IndicatorSetString(INDICATOR_SHORTNAME, "BT_Fibonacci(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
      {
         Fib236Buffer[i] = EMPTY_VALUE;
         Fib382Buffer[i] = EMPTY_VALUE;
         Fib500Buffer[i] = EMPTY_VALUE;
         Fib618Buffer[i] = EMPTY_VALUE;
         Fib786Buffer[i] = EMPTY_VALUE;
      }
   }

   for(int i = start; i < rates_total; i++)
   {
      double hh = high[i - InpPeriod + 1];
      double ll = low[i - InpPeriod + 1];
      for(int j = i - InpPeriod + 2; j <= i; j++)
      {
         if(high[j] > hh) hh = high[j];
         if(low[j]  < ll) ll = low[j];
      }
      double range = hh - ll;
      Fib236Buffer[i] = hh - range * 0.236;
      Fib382Buffer[i] = hh - range * 0.382;
      Fib500Buffer[i] = hh - range * 0.500;
      Fib618Buffer[i] = hh - range * 0.618;
      Fib786Buffer[i] = hh - range * 0.786;
   }

   return rates_total;
}
