//+------------------------------------------------------------------+
//|                                                BT_GannHiLo.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Gann HiLo Activator                                            |
//|   SMA(High,period) / SMA(Low,period), switches on close break    |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "GannHiLo"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrGold
#property indicator_width1  2

input int InpPeriod = 14; // Period

double GannBuffer[];

int OnInit()
{
   SetIndexBuffer(0, GannBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod - 1);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_GannHiLo(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   // Always recalc from start: is_bullish state is cumulative
   ArrayInitialize(GannBuffer, EMPTY_VALUE);

   bool isBullish = true;

   for(int i = InpPeriod - 1; i < rates_total; i++)
   {
      // SMA of High over window
      double sumH = 0, sumL = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
      {
         sumH += high[j];
         sumL += low[j];
      }
      double smaH = sumH / InpPeriod;
      double smaL = sumL / InpPeriod;

      if(close[i] > smaH)       isBullish = true;
      else if(close[i] < smaL)  isBullish = false;

      GannBuffer[i] = isBullish ? smaL : smaH;
   }

   return rates_total;
}
