//+------------------------------------------------------------------+
//|                                               BT_HeikenAshi.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   HA_Close = (O+H+L+C)/4                                        |
//|   HA_Open[0] = (O+C)/2, HA_Open[i] = (prev_HA_Open+prev_HA_Close)/2 |
//|   Buffer 0: HA_Close, Buffer 1: HA_Open                         |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 2
#property indicator_plots   2
#property indicator_label1  "HA_Close"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_label2  "HA_Open"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrOrangeRed
#property indicator_width2  1

double HaCloseBuffer[];
double HaOpenBuffer[];

int OnInit()
{
   SetIndexBuffer(0, HaCloseBuffer, INDICATOR_DATA);
   SetIndexBuffer(1, HaOpenBuffer,  INDICATOR_DATA);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   PlotIndexSetDouble(1, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_HeikenAshi");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 1) return 0;

   // Always recalc from start: HA_Open is stateful (depends on prev HA values)
   // First bar seed
   HaCloseBuffer[0] = (open[0] + high[0] + low[0] + close[0]) / 4.0;
   HaOpenBuffer[0]  = (open[0] + close[0]) / 2.0;

   for(int i = 1; i < rates_total; i++)
   {
      HaCloseBuffer[i] = (open[i] + high[i] + low[i] + close[i]) / 4.0;
      HaOpenBuffer[i]  = (HaOpenBuffer[i - 1] + HaCloseBuffer[i - 1]) / 2.0;
   }

   return rates_total;
}
