//+------------------------------------------------------------------+
//|                                                  BT_HullMA.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Hull Moving Average = WMA(2*WMA(n/2) - WMA(n), sqrt(n))       |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "HullMA"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrLimeGreen
#property indicator_width1  2

input int InpPeriod = 16; // Period

double HullBuffer[];

// -----------------------------------------------------------------------
// WMA helper: computes WMA of src[0..n-1] where src[n-1] is most recent
// weights: 1 (oldest) .. n (newest), denom = n*(n+1)/2
// -----------------------------------------------------------------------
double CalcWMA(const double &src[], int endIdx, int n)
{
   double weightedSum = 0;
   double denom       = (double)n * (n + 1) / 2.0;
   for(int j = 0; j < n; j++)
   {
      weightedSum += (double)(j + 1) * src[endIdx - n + 1 + j];
   }
   return weightedSum / denom;
}

int OnInit()
{
   SetIndexBuffer(0, HullBuffer, INDICATOR_DATA);
   int minBars = InpPeriod + (int)MathFloor(MathSqrt((double)InpPeriod));
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, minBars - 1);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_HullMA(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   int half   = MathMax(InpPeriod / 2, 1);
   int sqrtP  = MathMax((int)MathFloor(MathSqrt((double)InpPeriod)), 1);
   int minBars = InpPeriod + sqrtP - 1;

   if(rates_total < minBars) return 0;

   // Build diff array: diff[i] = 2*WMA(close, half, i) - WMA(close, InpPeriod, i)
   // We need at least rates_total entries; allocate dynamic array
   double diff[];
   ArrayResize(diff, rates_total);
   ArrayInitialize(diff, 0);

   int start = (prev_calculated == 0) ? 0 : prev_calculated - 1;

   // For hull we always recalc from InpPeriod-1 onwards to keep diff consistent
   // But for performance when incremental, recompute only affected range
   int diffStart = (prev_calculated == 0) ? InpPeriod - 1 : MathMax(prev_calculated - 1, InpPeriod - 1);

   for(int i = diffStart; i < rates_total; i++)
   {
      double wmaHalf = CalcWMA(close, i, half);
      double wmaFull = CalcWMA(close, i, InpPeriod);
      diff[i] = 2.0 * wmaHalf - wmaFull;
   }

   // Now compute WMA(diff, sqrtP) starting from InpPeriod + sqrtP - 2
   int hullStart = (prev_calculated == 0) ? (InpPeriod + sqrtP - 2) : MathMax(prev_calculated - 1, InpPeriod + sqrtP - 2);

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod + sqrtP - 2; i++)
         HullBuffer[i] = EMPTY_VALUE;
   }

   for(int i = hullStart; i < rates_total; i++)
   {
      HullBuffer[i] = CalcWMA(diff, i, sqrtP);
   }

   return rates_total;
}
