//+------------------------------------------------------------------+
//|                                               BT_Ichimoku.mq5    |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Ichimoku Kinko Hyo                                             |
//|   Buffer 0=Tenkan, 1=Kijun, 2=SenkouA, 3=SenkouB, 4=Chikou     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 5
#property indicator_plots   5
#property indicator_label1  "Tenkan"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrRed
#property indicator_width1  1
#property indicator_label2  "Kijun"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrBlue
#property indicator_width2  1
#property indicator_label3  "SenkouA"
#property indicator_type3   DRAW_LINE
#property indicator_color3  clrLimeGreen
#property indicator_width3  1
#property indicator_label4  "SenkouB"
#property indicator_type4   DRAW_LINE
#property indicator_color4  clrOrangeRed
#property indicator_width4  1
#property indicator_label5  "Chikou"
#property indicator_type5   DRAW_LINE
#property indicator_color5  clrGray
#property indicator_width5  1

input int InpTenkan = 9;  // Tenkan Period
input int InpKijun  = 26; // Kijun Period
input int InpSenkou = 52; // Senkou B Period

double TenkanBuffer[];
double KijunBuffer[];
double SenkouABuffer[];
double SenkouBBuffer[];
double ChikouBuffer[];

// Midpoint of highest high and lowest low over p bars ending at idx
double Midpoint(const double &high[], const double &low[], int idx, int p)
{
   double hh = high[idx - p + 1];
   double ll = low[idx - p + 1];
   for(int j = idx - p + 2; j <= idx; j++)
   {
      if(high[j] > hh) hh = high[j];
      if(low[j]  < ll) ll = low[j];
   }
   return (hh + ll) / 2.0;
}

int OnInit()
{
   SetIndexBuffer(0, TenkanBuffer,  INDICATOR_DATA);
   SetIndexBuffer(1, KijunBuffer,   INDICATOR_DATA);
   SetIndexBuffer(2, SenkouABuffer, INDICATOR_DATA);
   SetIndexBuffer(3, SenkouBBuffer, INDICATOR_DATA);
   SetIndexBuffer(4, ChikouBuffer,  INDICATOR_DATA);

   int maxPeriod = MathMax(InpSenkou, MathMax(InpTenkan, InpKijun));
   for(int p = 0; p < 5; p++)
   {
      PlotIndexSetInteger(p, PLOT_DRAW_BEGIN, maxPeriod + InpKijun - 1);
      PlotIndexSetDouble(p,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   }

   IndicatorSetString(INDICATOR_SHORTNAME,
      "BT_Ichimoku(" + IntegerToString(InpTenkan) + "," +
      IntegerToString(InpKijun) + "," + IntegerToString(InpSenkou) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   int maxP = MathMax(InpSenkou, MathMax(InpTenkan, InpKijun));
   if(rates_total < maxP + InpKijun) return 0;

   int start = (prev_calculated == 0) ? 0 : prev_calculated - 1;

   if(prev_calculated == 0)
      ArrayInitialize(TenkanBuffer, EMPTY_VALUE),
      ArrayInitialize(KijunBuffer,  EMPTY_VALUE),
      ArrayInitialize(SenkouABuffer,EMPTY_VALUE),
      ArrayInitialize(SenkouBBuffer,EMPTY_VALUE),
      ArrayInitialize(ChikouBuffer, EMPTY_VALUE);

   for(int i = start; i < rates_total; i++)
   {
      // Tenkan
      if(i >= InpTenkan - 1)
         TenkanBuffer[i] = Midpoint(high, low, i, InpTenkan);

      // Kijun
      if(i >= InpKijun - 1)
         KijunBuffer[i] = Midpoint(high, low, i, InpKijun);

      // Senkou A: (Tenkan + Kijun) / 2, plotted InpKijun periods ahead
      // Here we store at current index i, representing the value for bar i+InpKijun
      // To keep no lookahead: output senkou_a at i using tenkan[i-kijun] and kijun[i-kijun]
      if(i >= InpKijun + InpTenkan - 2)
      {
         int src = i - InpKijun;
         if(src >= InpTenkan - 1 && src >= InpKijun - 1)
         {
            double t = Midpoint(high, low, src, InpTenkan);
            double k = Midpoint(high, low, src, InpKijun);
            SenkouABuffer[i] = (t + k) / 2.0;
         }
      }

      // Senkou B: midpoint over senkou_period, shifted back InpKijun
      if(i >= InpKijun + InpSenkou - 2)
      {
         int src = i - InpKijun;
         if(src >= InpSenkou - 1)
            SenkouBBuffer[i] = Midpoint(high, low, src, InpSenkou);
      }

      // Chikou: simply the close (no lookahead)
      ChikouBuffer[i] = close[i];
   }

   return rates_total;
}
