//+------------------------------------------------------------------+
//|                                          BT_KeltnerChannel.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Middle = EMA(Close, period)                                    |
//|   Upper  = Middle + Multiplier * ATR(Wilder)                     |
//|   Lower  = Middle - Multiplier * ATR(Wilder)                     |
//|   Buffer 0=Middle, 1=Upper, 2=Lower                              |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 3
#property indicator_plots   3
#property indicator_label1  "KC_Middle"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrGold
#property indicator_width1  1
#property indicator_label2  "KC_Upper"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrDodgerBlue
#property indicator_width2  1
#property indicator_label3  "KC_Lower"
#property indicator_type3   DRAW_LINE
#property indicator_color3  clrRed
#property indicator_width3  1

input int    InpPeriod     = 20;  // EMA / ATR Period
input double InpMultiplier = 1.5; // ATR Multiplier

double MiddleBuffer[];
double UpperBuffer[];
double LowerBuffer[];

// EMA and ATR states
double gEma = 0;
double gAtr = 0;

int OnInit()
{
   SetIndexBuffer(0, MiddleBuffer, INDICATOR_DATA);
   SetIndexBuffer(1, UpperBuffer,  INDICATOR_DATA);
   SetIndexBuffer(2, LowerBuffer,  INDICATOR_DATA);

   for(int p = 0; p < 3; p++)
   {
      PlotIndexSetInteger(p, PLOT_DRAW_BEGIN, InpPeriod);
      PlotIndexSetDouble(p,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   }

   IndicatorSetString(INDICATOR_SHORTNAME,
      "BT_KeltnerChannel(" + IntegerToString(InpPeriod) + "," +
      DoubleToString(InpMultiplier, 1) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   double emaMultiplier = 2.0 / (InpPeriod + 1.0);

   int start;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
      {
         MiddleBuffer[i] = EMPTY_VALUE;
         UpperBuffer[i]  = EMPTY_VALUE;
         LowerBuffer[i]  = EMPTY_VALUE;
      }

      // Seed EMA with SMA of first period closes
      double sumClose = 0;
      for(int i = 0; i < InpPeriod; i++)
         sumClose += close[i];
      gEma = sumClose / InpPeriod;

      // Seed ATR (Wilder): SMA of first period TR values
      // TR[0] = high[0] - low[0]
      double sumTR = high[0] - low[0];
      for(int i = 1; i < InpPeriod; i++)
      {
         double hl = high[i] - low[i];
         double hc = MathAbs(high[i] - close[i - 1]);
         double lc = MathAbs(low[i]  - close[i - 1]);
         sumTR += MathMax(hl, MathMax(hc, lc));
      }
      gAtr = sumTR / InpPeriod;

      MiddleBuffer[InpPeriod - 1] = gEma;
      UpperBuffer[InpPeriod - 1]  = gEma + InpMultiplier * gAtr;
      LowerBuffer[InpPeriod - 1]  = gEma - InpMultiplier * gAtr;
      start = InpPeriod;
   }
   else
   {
      start = prev_calculated - 1;
   }

   for(int i = start; i < rates_total; i++)
   {
      // Update EMA
      gEma = (close[i] - gEma) * emaMultiplier + gEma;

      // Update ATR (Wilder)
      double hl = high[i] - low[i];
      double hc = MathAbs(high[i] - close[i - 1]);
      double lc = MathAbs(low[i]  - close[i - 1]);
      double tr = MathMax(hl, MathMax(hc, lc));
      gAtr = (gAtr * (InpPeriod - 1) + tr) / InpPeriod;

      MiddleBuffer[i] = gEma;
      UpperBuffer[i]  = gEma + InpMultiplier * gAtr;
      LowerBuffer[i]  = gEma - InpMultiplier * gAtr;
   }

   return rates_total;
}
