//+------------------------------------------------------------------+
//|                                              BT_LaguerreRSI.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Laguerre RSI (0..1 range), gamma parameter                    |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "LaguerreRSI"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_level1  0.8
#property indicator_level2  0.2
#property indicator_minimum 0
#property indicator_maximum 1

input double InpGamma = 0.8; // Gamma

double LagrBuffer[];

int OnInit()
{
   SetIndexBuffer(0, LagrBuffer, INDICATOR_DATA);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME,
      "BT_LaguerreRSI(" + DoubleToString(InpGamma, 2) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 1) return 0;

   // Always recalc from start — purely stateful
   double l0 = 0, l1 = 0, l2 = 0, l3 = 0;

   for(int i = 0; i < rates_total; i++)
   {
      double prev_l0 = l0;
      double prev_l1 = l1;
      double prev_l2 = l2;

      l0 = (1.0 - InpGamma) * close[i] + InpGamma * prev_l0;
      l1 = -InpGamma * l0 + prev_l0 + InpGamma * prev_l1;
      l2 = -InpGamma * l1 + prev_l1 + InpGamma * prev_l2;
      l3 = -InpGamma * l2 + prev_l2 + InpGamma * l3;

      double cu = 0, cd = 0;
      if(l0 >= l1) cu += l0 - l1; else cd += l1 - l0;
      if(l1 >= l2) cu += l1 - l2; else cd += l2 - l1;
      if(l2 >= l3) cu += l2 - l3; else cd += l3 - l2;

      double total = cu + cd;
      LagrBuffer[i] = (total != 0) ? cu / total : 0;
   }

   return rates_total;
}
