//+------------------------------------------------------------------+
//|                                        BT_LinearRegression.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Fits y = a + b*x over rolling window, outputs fitted value     |
//|   at last bar (x = period-1).                                    |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "LinReg"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrMagenta
#property indicator_width1  1

input int InpPeriod = 14; // Period

double LinRegBuffer[];

int OnInit()
{
   SetIndexBuffer(0, LinRegBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod - 1);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_LinReg(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int n = InpPeriod;

   // Precompute fixed sums for x: 0,1,...,n-1
   double sum_x  = (double)n * (n - 1) / 2.0;
   double sum_x2 = 0;
   for(int j = 0; j < n; j++)
      sum_x2 += (double)j * j;
   double denom = (double)n * sum_x2 - sum_x * sum_x;

   int start = (prev_calculated == 0) ? n - 1 : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < n - 1; i++)
         LinRegBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      double sum_y  = 0;
      double sum_xy = 0;
      for(int j = 0; j < n; j++)
      {
         double y = close[i - n + 1 + j];
         sum_y  += y;
         sum_xy += (double)j * y;
      }
      double b      = (denom != 0) ? ((double)n * sum_xy - sum_x * sum_y) / denom : 0;
      double a      = (sum_y - b * sum_x) / (double)n;
      LinRegBuffer[i] = a + b * (double)(n - 1);
   }

   return rates_total;
}
