//+------------------------------------------------------------------+
//|                                                 BT_Momentum.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Momentum = Close[i] - Close[i - period]                        |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "Momentum"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1

input int InpPeriod = 14; // Period

double MomBuffer[];

int OnInit()
{
   SetIndexBuffer(0, MomBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_Momentum(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   int start = (prev_calculated == 0) ? InpPeriod : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod; i++)
         MomBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      MomBuffer[i] = close[i] - close[i - InpPeriod];
   }

   return rates_total;
}
