//+------------------------------------------------------------------+
//|                                                  BT_Pivots.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Classic Daily Pivot Points based on previous day H/L/C         |
//|   Buffer 0=PP, 1=R1, 2=S1, 3=R2, 4=S2                          |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 5
#property indicator_plots   5
#property indicator_label1  "PP"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrGold
#property indicator_style1  STYLE_DASH
#property indicator_width1  1
#property indicator_label2  "R1"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrDodgerBlue
#property indicator_style2  STYLE_DOT
#property indicator_width2  1
#property indicator_label3  "S1"
#property indicator_type3   DRAW_LINE
#property indicator_color3  clrRed
#property indicator_style3  STYLE_DOT
#property indicator_width3  1
#property indicator_label4  "R2"
#property indicator_type4   DRAW_LINE
#property indicator_color4  clrCornflowerBlue
#property indicator_style4  STYLE_DOT
#property indicator_width4  1
#property indicator_label5  "S2"
#property indicator_type5   DRAW_LINE
#property indicator_color5  clrLightCoral
#property indicator_style5  STYLE_DOT
#property indicator_width5  1

double PpBuffer[];
double R1Buffer[];
double S1Buffer[];
double R2Buffer[];
double S2Buffer[];

int OnInit()
{
   SetIndexBuffer(0, PpBuffer, INDICATOR_DATA);
   SetIndexBuffer(1, R1Buffer, INDICATOR_DATA);
   SetIndexBuffer(2, S1Buffer, INDICATOR_DATA);
   SetIndexBuffer(3, R2Buffer, INDICATOR_DATA);
   SetIndexBuffer(4, S2Buffer, INDICATOR_DATA);

   for(int p = 0; p < 5; p++)
      PlotIndexSetDouble(p, PLOT_EMPTY_VALUE, EMPTY_VALUE);

   IndicatorSetString(INDICATOR_SHORTNAME, "BT_Pivots");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 2) return 0;

   // Always recalc: day-boundary detection is stateful
   ArrayInitialize(PpBuffer, EMPTY_VALUE);
   ArrayInitialize(R1Buffer, EMPTY_VALUE);
   ArrayInitialize(S1Buffer, EMPTY_VALUE);
   ArrayInitialize(R2Buffer, EMPTY_VALUE);
   ArrayInitialize(S2Buffer, EMPTY_VALUE);

   // Current pivot values, initialized from first bar's own data
   // (no previous day available for bar 0)
   double pp = 0, r1 = 0, s1 = 0, r2 = 0, s2 = 0;
   bool   hasPivots = false;

   // Track current-day accumulated H/L/C (use last close of prev day)
   double prevDayH = 0, prevDayL = 0, prevDayC = 0;

   // Extract date from timestamp
   MqlDateTime dt0, dt1;
   TimeToStruct(time[0], dt0);
   int prevDay = dt0.day;
   int prevMon = dt0.mon;
   int prevYr  = dt0.year;

   prevDayH = high[0];
   prevDayL = low[0];
   prevDayC = close[0];

   for(int i = 1; i < rates_total; i++)
   {
      TimeToStruct(time[i], dt1);

      bool newDay = (dt1.day  != prevDay ||
                     dt1.mon  != prevMon ||
                     dt1.year != prevYr);

      if(newDay)
      {
         // Compute pivots from previous day
         pp = (prevDayH + prevDayL + prevDayC) / 3.0;
         r1 = 2.0 * pp - prevDayL;
         s1 = 2.0 * pp - prevDayH;
         r2 = pp + (prevDayH - prevDayL);
         s2 = pp - (prevDayH - prevDayL);
         hasPivots = true;

         // Reset tracking for new day
         prevDayH = high[i];
         prevDayL = low[i];
         prevDayC = close[i];
         prevDay  = dt1.day;
         prevMon  = dt1.mon;
         prevYr   = dt1.year;
      }
      else
      {
         // Accumulate intraday H/L/C for end-of-day pivot calculation
         if(high[i]  > prevDayH) prevDayH = high[i];
         if(low[i]   < prevDayL) prevDayL = low[i];
         prevDayC = close[i];
      }

      if(hasPivots)
      {
         PpBuffer[i] = pp;
         R1Buffer[i] = r1;
         S1Buffer[i] = s1;
         R2Buffer[i] = r2;
         S2Buffer[i] = s2;
      }
   }

   return rates_total;
}
