//+------------------------------------------------------------------+
//|                                                      BT_ROC.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact ROC calculation from backtester engine.        |
//|   ROC = (Close - Close[N]) / Close[N] * 100                      |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "ROC"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_level1  0

input int InpPeriod = 12; // Period

double RocBuffer[];

int OnInit()
{
   SetIndexBuffer(0, RocBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod + 1);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_ROC(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   int start = (prev_calculated == 0) ? InpPeriod : prev_calculated - 1;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod; i++)
         RocBuffer[i] = EMPTY_VALUE;
   }

   // ROC = (close - close[n]) / close[n] * 100
   for(int i = start; i < rates_total; i++)
   {
      if(close[i - InpPeriod] != 0)
         RocBuffer[i] = (close[i] - close[i - InpPeriod]) / close[i - InpPeriod] * 100.0;
      else
         RocBuffer[i] = 0;
   }

   return rates_total;
}
