//+------------------------------------------------------------------+
//|                                                      BT_RSI.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact RSI calculation from backtester engine.        |
//|   Uses Wilder's smoothing method for avg gain/loss.               |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "RSI"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrMediumPurple
#property indicator_width1  1
#property indicator_level1  70
#property indicator_level2  30
#property indicator_minimum 0
#property indicator_maximum 100

input int InpPeriod = 14; // Period

double RsiBuffer[];

// Internal state for Wilder's smoothing
double gAvgGain = 0;
double gAvgLoss = 0;
bool   gSeeded  = false;

int OnInit()
{
   SetIndexBuffer(0, RsiBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod + 1);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_RSI(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   int start;
   if(prev_calculated == 0)
   {
      for(int i = 0; i <= InpPeriod; i++)
         RsiBuffer[i] = EMPTY_VALUE;

      // First average: simple average of first 'period' changes
      double sumGain = 0, sumLoss = 0;
      for(int i = 1; i <= InpPeriod; i++)
      {
         double change = close[i] - close[i - 1];
         if(change > 0) sumGain += change;
         else           sumLoss += (-change);
      }
      gAvgGain = sumGain / InpPeriod;
      gAvgLoss = sumLoss / InpPeriod;
      gSeeded = true;

      if(gAvgLoss == 0)
         RsiBuffer[InpPeriod] = 100.0;
      else
         RsiBuffer[InpPeriod] = 100.0 - 100.0 / (1.0 + gAvgGain / gAvgLoss);

      start = InpPeriod + 1;
   }
   else
   {
      start = prev_calculated - 1;
   }

   // Wilder's smoothing: avgGain = (prev*(period-1) + current) / period
   for(int i = start; i < rates_total; i++)
   {
      double change = close[i] - close[i - 1];
      double gain = (change > 0) ? change : 0;
      double loss = (change < 0) ? (-change) : 0;

      gAvgGain = (gAvgGain * (InpPeriod - 1) + gain) / InpPeriod;
      gAvgLoss = (gAvgLoss * (InpPeriod - 1) + loss) / InpPeriod;

      if(gAvgLoss == 0)
         RsiBuffer[i] = 100.0;
      else
         RsiBuffer[i] = 100.0 - 100.0 / (1.0 + gAvgGain / gAvgLoss);
   }

   return rates_total;
}
