//+------------------------------------------------------------------+
//|                                                  BT_Reflex.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Ehlers Reflex Indicator (Super Smoother + Reflex)              |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "Reflex"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1

input int InpPeriod = 20; // Period

double ReflexBuffer[];

int OnInit()
{
   SetIndexBuffer(0, ReflexBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_Reflex(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   // Always recalc from start: stateful filter
   ArrayInitialize(ReflexBuffer, EMPTY_VALUE);

   const double PI = 3.14159265358979;
   double a1     = MathExp(-MathSqrt(2.0) * PI / InpPeriod);
   double coeff2 = 2.0 * a1 * MathCos(MathSqrt(2.0) * PI / InpPeriod);
   double coeff3 = -(a1 * a1);
   double coeff1 = 1.0 - coeff2 - coeff3;

   // Build Super Smoother filter
   double filt[];
   ArrayResize(filt, rates_total);
   filt[0] = close[0];
   if(rates_total > 1) filt[1] = close[1];

   for(int i = 2; i < rates_total; i++)
   {
      filt[i] = coeff1 * (close[i] + close[i - 1]) / 2.0
              + coeff2 * filt[i - 1]
              + coeff3 * filt[i - 2];
   }

   // Compute Reflex
   double ms = 0;
   for(int i = InpPeriod; i < rates_total; i++)
   {
      double slope = (filt[i - InpPeriod] - filt[i]) / (double)InpPeriod;
      double sum   = 0;
      for(int j = 1; j <= InpPeriod; j++)
      {
         sum += filt[i] + (double)j * slope - filt[i - j];
      }
      sum /= (double)InpPeriod;

      ms = 0.04 * sum * sum + 0.96 * ms;
      ReflexBuffer[i] = (ms > 0) ? sum / MathSqrt(ms) : 0;
   }

   return rates_total;
}
