//+------------------------------------------------------------------+
//|                                                      BT_SMA.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact SMA calculation from backtester engine.        |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "SMA"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1

input int InpPeriod = 14; // Period

double SmaBuffer[];

int OnInit()
{
   SetIndexBuffer(0, SmaBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_SMA(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         SmaBuffer[i] = EMPTY_VALUE;

      // First SMA: simple sum of first 'period' closes
      double sum = 0;
      for(int i = 0; i < InpPeriod; i++)
         sum += close[i];
      SmaBuffer[InpPeriod - 1] = sum / InpPeriod;
      start = InpPeriod;
   }
   else
   {
      start = prev_calculated - 1;
   }

   // Rolling SMA using add/subtract
   for(int i = start; i < rates_total; i++)
   {
      SmaBuffer[i] = SmaBuffer[i - 1] + (close[i] - close[i - InpPeriod]) / InpPeriod;
   }

   return rates_total;
}
