//+------------------------------------------------------------------+
//|                                               BT_SuperTrend.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   SuperTrend indicator using Wilder's ATR                        |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "SuperTrend"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrGold
#property indicator_width1  2

input int    InpPeriod     = 7;   // ATR Period
input double InpMultiplier = 3.0; // Multiplier

double StBuffer[];

int OnInit()
{
   SetIndexBuffer(0, StBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME,
      "BT_SuperTrend(" + IntegerToString(InpPeriod) + "," +
      DoubleToString(InpMultiplier, 1) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   // Always recalc from start: stateful (finalUpper/Lower and direction)
   ArrayInitialize(StBuffer, EMPTY_VALUE);

   // ---- Build Wilder's ATR array ----
   double atr[];
   ArrayResize(atr, rates_total);
   ArrayInitialize(atr, 0);

   // TR[0] = high[0] - low[0]
   double sumTR = high[0] - low[0];
   for(int i = 1; i < InpPeriod; i++)
   {
      double hl = high[i] - low[i];
      double hc = MathAbs(high[i] - close[i - 1]);
      double lc = MathAbs(low[i]  - close[i - 1]);
      sumTR += MathMax(hl, MathMax(hc, lc));
   }
   atr[InpPeriod - 1] = sumTR / InpPeriod;

   for(int i = InpPeriod; i < rates_total; i++)
   {
      double hl = high[i] - low[i];
      double hc = MathAbs(high[i] - close[i - 1]);
      double lc = MathAbs(low[i]  - close[i - 1]);
      double tr = MathMax(hl, MathMax(hc, lc));
      atr[i] = (atr[i - 1] * (InpPeriod - 1) + tr) / InpPeriod;
   }

   // ---- SuperTrend ----
   double finalUpper    = 0;
   double finalLower    = 0;
   bool   stIsUpper     = true; // true = bearish (upper band active)
   bool   firstValid    = true;

   for(int i = InpPeriod - 1; i < rates_total; i++)
   {
      double hl2         = (high[i] + low[i]) / 2.0;
      double basicUpper  = hl2 + InpMultiplier * atr[i];
      double basicLower  = hl2 - InpMultiplier * atr[i];

      if(firstValid)
      {
         finalUpper   = basicUpper;
         finalLower   = basicLower;
         stIsUpper    = (close[i] <= basicUpper);
         firstValid   = false;
      }
      else
      {
         double prevFinalUpper = finalUpper;
         double prevFinalLower = finalLower;
         double prevClose      = close[i - 1];

         // Adjust final upper
         if(basicUpper < prevFinalUpper || prevClose > prevFinalUpper)
            finalUpper = basicUpper;
         else
            finalUpper = prevFinalUpper;

         // Adjust final lower
         if(basicLower > prevFinalLower || prevClose < prevFinalLower)
            finalLower = basicLower;
         else
            finalLower = prevFinalLower;

         // Switch direction
         if(stIsUpper)
         {
            if(close[i] > finalUpper)
               stIsUpper = false;
         }
         else
         {
            if(close[i] < finalLower)
               stIsUpper = true;
         }
      }

      StBuffer[i] = stIsUpper ? finalUpper : finalLower;
   }

   return rates_total;
}
