//+------------------------------------------------------------------+
//|                                             BT_SmallestRange.mq5 |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Smallest H-L range over rolling period bars                    |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "SmallestRange"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1

input int InpPeriod = 14; // Period

double SmallRangeBuffer[];

int OnInit()
{
   SetIndexBuffer(0, SmallRangeBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod - 1);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_SmallestRange(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         SmallRangeBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      double minRange = high[i - InpPeriod + 1] - low[i - InpPeriod + 1];
      for(int j = i - InpPeriod + 2; j <= i; j++)
      {
         double r = high[j] - low[j];
         if(r < minRange) minRange = r;
      }
      SmallRangeBuffer[i] = minRange;
   }

   return rates_total;
}
