//+------------------------------------------------------------------+
//|                                              BT_Stochastic.mq5    |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact Stochastic calculation from backtester engine. |
//|   %K = (Close - LowestLow) / (HighestHigh - LowestLow) * 100     |
//|   %D = SMA of %K                                                  |
//|   Buffer 0: %K, Buffer 1: %D                                      |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 2
#property indicator_plots   2
#property indicator_label1  "%K"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_label2  "%D"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrRed
#property indicator_width2  1
#property indicator_level1  80
#property indicator_level2  20
#property indicator_minimum 0
#property indicator_maximum 100

input int InpKPeriod = 14; // %K Period
input int InpDPeriod = 3;  // %D Period (SMA of %K)

double KBuffer[];
double DBuffer[];

int OnInit()
{
   SetIndexBuffer(0, KBuffer, INDICATOR_DATA);
   SetIndexBuffer(1, DBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpKPeriod);
   PlotIndexSetInteger(1, PLOT_DRAW_BEGIN, InpKPeriod + InpDPeriod - 1);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   PlotIndexSetDouble(1, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME,
      "BT_Stoch(" + IntegerToString(InpKPeriod) + "," + IntegerToString(InpDPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpKPeriod) return 0;

   int start = (prev_calculated == 0) ? InpKPeriod - 1 : prev_calculated - 1;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpKPeriod - 1; i++)
      {
         KBuffer[i] = EMPTY_VALUE;
         DBuffer[i] = EMPTY_VALUE;
      }
   }

   // Compute %K
   for(int i = start; i < rates_total; i++)
   {
      double highest = high[i];
      double lowest  = low[i];
      for(int j = i - InpKPeriod + 1; j < i; j++)
      {
         if(high[j] > highest) highest = high[j];
         if(low[j] < lowest)   lowest  = low[j];
      }
      double range = highest - lowest;
      KBuffer[i] = (range == 0) ? 50.0 : (close[i] - lowest) / range * 100.0;
   }

   // Compute %D = SMA of %K
   int dStart = (prev_calculated == 0) ? InpKPeriod + InpDPeriod - 2 : prev_calculated - 1;
   if(prev_calculated == 0)
   {
      for(int i = InpKPeriod - 1; i < InpKPeriod + InpDPeriod - 2 && i < rates_total; i++)
         DBuffer[i] = EMPTY_VALUE;
   }

   for(int i = dStart; i < rates_total; i++)
   {
      double sum = 0;
      bool valid = true;
      for(int j = i - InpDPeriod + 1; j <= i; j++)
      {
         if(KBuffer[j] == EMPTY_VALUE) { valid = false; break; }
         sum += KBuffer[j];
      }
      DBuffer[i] = valid ? sum / InpDPeriod : EMPTY_VALUE;
   }

   return rates_total;
}
