//+------------------------------------------------------------------+
//|                                                   BT_StdDev.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Population StdDev of Close over period bars (divide by N)      |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "StdDev"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1

input int InpPeriod = 20; // Period

double StdDevBuffer[];

int OnInit()
{
   SetIndexBuffer(0, StdDevBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod - 1);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_StdDev(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         StdDevBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      double sum = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
         sum += close[j];
      double mean = sum / InpPeriod;

      double varSum = 0;
      for(int j = i - InpPeriod + 1; j <= i; j++)
      {
         double diff = close[j] - mean;
         varSum += diff * diff;
      }
      StdDevBuffer[i] = MathSqrt(varSum / InpPeriod);
   }

   return rates_total;
}
