//+------------------------------------------------------------------+
//|                                               BT_TrueRange.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   TR[0] = High-Low, TR[i] = max(H-L, |H-prevC|, |L-prevC|)     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "TrueRange"
#property indicator_type1   DRAW_HISTOGRAM
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1

double TrBuffer[];

int OnInit()
{
   SetIndexBuffer(0, TrBuffer, INDICATOR_DATA);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_TrueRange");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 1) return 0;

   int start = (prev_calculated == 0) ? 0 : prev_calculated - 1;

   for(int i = start; i < rates_total; i++)
   {
      if(i == 0)
      {
         TrBuffer[0] = high[0] - low[0];
      }
      else
      {
         double hl = high[i] - low[i];
         double hc = MathAbs(high[i] - close[i - 1]);
         double lc = MathAbs(low[i]  - close[i - 1]);
         TrBuffer[i] = MathMax(hl, MathMax(hc, lc));
      }
   }

   return rates_total;
}
