//+------------------------------------------------------------------+
//|                                               BT_UlcerIndex.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Ulcer Index = sqrt(mean of squared % drawdowns from running max)|
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "UlcerIndex"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrOrangeRed
#property indicator_width1  1

input int InpPeriod = 14; // Period

double UlcerBuffer[];

int OnInit()
{
   SetIndexBuffer(0, UlcerBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod - 1);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_UlcerIndex(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;

   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         UlcerBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      // Compute running max within window, accumulate squared % drawdowns
      double runningMax = close[i - InpPeriod + 1];
      double sumSq      = 0;

      for(int j = i - InpPeriod + 1; j <= i; j++)
      {
         if(close[j] > runningMax) runningMax = close[j];
         if(runningMax > 0)
         {
            double pctDD = (close[j] - runningMax) / runningMax * 100.0;
            sumSq += pctDD * pctDD;
         }
      }

      UlcerBuffer[i] = MathSqrt(sumSq / InpPeriod);
   }

   return rates_total;
}
