//+------------------------------------------------------------------+
//|                                                     BT_VWAP.mq5  |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact VWAP calculation from backtester engine.       |
//|   VWAP = cumulative(TP * Volume) / cumulative(Volume)             |
//|   Resets daily at midnight (new trading day).                      |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_chart_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "VWAP"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrGold
#property indicator_width1  2

double VwapBuffer[];

int OnInit()
{
   SetIndexBuffer(0, VwapBuffer, INDICATOR_DATA);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_VWAP");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 1) return 0;

   int start = (prev_calculated == 0) ? 0 : prev_calculated - 1;

   // For full recalc, we need to iterate from the beginning
   // because VWAP is path-dependent (cumulative) and resets daily
   if(prev_calculated == 0)
   {
      double cumVol   = 0;
      double cumTpVol = 0;
      int prevDay = -1;

      for(int i = 0; i < rates_total; i++)
      {
         MqlDateTime dt;
         TimeToStruct(time[i], dt);
         int currentDay = dt.day_of_year;

         // Reset on new day
         if(currentDay != prevDay)
         {
            cumVol   = 0;
            cumTpVol = 0;
            prevDay  = currentDay;
         }

         double tp = (high[i] + low[i] + close[i]) / 3.0;
         // Use tick_volume as volume proxy (matches backtester behavior)
         double vol = (double)tick_volume[i];

         cumTpVol += tp * vol;
         cumVol   += vol;

         VwapBuffer[i] = (cumVol == 0) ? tp : cumTpVol / cumVol;
      }
   }
   else
   {
      // Incremental: recalc only new bars
      // We need cumulative state — force full recalc for simplicity
      // (VWAP resets daily, so partial updates are complex)
      return 0;
   }

   return rates_total;
}
