//+------------------------------------------------------------------+
//|                                                  BT_Vortex.mq5   |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Vortex Indicator: VI+ and VI-                                  |
//|   Buffer 0=VI+, Buffer 1=VI-                                     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 2
#property indicator_plots   2
#property indicator_label1  "VI+"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_width1  1
#property indicator_label2  "VI-"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrRed
#property indicator_width2  1

input int InpPeriod = 14; // Period

double ViPlusBuffer[];
double ViMinusBuffer[];

int OnInit()
{
   SetIndexBuffer(0, ViPlusBuffer,  INDICATOR_DATA);
   SetIndexBuffer(1, ViMinusBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetInteger(1, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   PlotIndexSetDouble(1,  PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_Vortex(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod + 1) return 0;

   // Always recalc from start for correctness
   ArrayInitialize(ViPlusBuffer,  EMPTY_VALUE);
   ArrayInitialize(ViMinusBuffer, EMPTY_VALUE);

   for(int i = InpPeriod; i < rates_total; i++)
   {
      double sumVmPlus  = 0;
      double sumVmMinus = 0;
      double sumTr      = 0;

      for(int j = i - InpPeriod + 1; j <= i; j++)
      {
         // VM+ and VM-
         sumVmPlus  += MathAbs(high[j] - low[j - 1]);
         sumVmMinus += MathAbs(low[j]  - high[j - 1]);

         // TR
         double hl = high[j] - low[j];
         double hc = MathAbs(high[j] - close[j - 1]);
         double lc = MathAbs(low[j]  - close[j - 1]);
         sumTr += MathMax(hl, MathMax(hc, lc));
      }

      if(sumTr != 0)
      {
         ViPlusBuffer[i]  = sumVmPlus  / sumTr;
         ViMinusBuffer[i] = sumVmMinus / sumTr;
      }
      else
      {
         ViPlusBuffer[i]  = 0;
         ViMinusBuffer[i] = 0;
      }
   }

   return rates_total;
}
