//+------------------------------------------------------------------+
//|                                               BT_WilliamsR.mq5    |
//|              Custom indicator — Generated by Backtester Rust      |
//|   Replicates exact Williams %R from backtester engine.            |
//|   WR = (HighestHigh - Close) / (HighestHigh - LowestLow) * -100  |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtester Rust"
#property version   "1.00"
#property strict
#property indicator_separate_window
#property indicator_buffers 1
#property indicator_plots   1
#property indicator_label1  "Williams %R"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrLimeGreen
#property indicator_width1  1
#property indicator_level1  -20
#property indicator_level2  -80
#property indicator_minimum -100
#property indicator_maximum 0

input int InpPeriod = 14; // Period

double WprBuffer[];

int OnInit()
{
   SetIndexBuffer(0, WprBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_DRAW_BEGIN, InpPeriod);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   IndicatorSetString(INDICATOR_SHORTNAME, "BT_WPR(" + IntegerToString(InpPeriod) + ")");
   return INIT_SUCCEEDED;
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < InpPeriod) return 0;

   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;
   if(prev_calculated == 0)
   {
      for(int i = 0; i < InpPeriod - 1; i++)
         WprBuffer[i] = EMPTY_VALUE;
   }

   for(int i = start; i < rates_total; i++)
   {
      double highest = high[i];
      double lowest  = low[i];
      for(int j = i - InpPeriod + 1; j < i; j++)
      {
         if(high[j] > highest) highest = high[j];
         if(low[j] < lowest)   lowest  = low[j];
      }
      double range = highest - lowest;
      WprBuffer[i] = (range == 0) ? -50.0 : (highest - close[i]) / range * (-100.0);
   }

   return rates_total;
}
